name: authentication_repository
description: Repository to manage user authentication.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.4.3"

dependencies:
  firebase_auth: ^6.5.6
  firebase_core: ^4.12.1
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.3.0