// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Real project (my-flutter-init, dedicated "io-pinball" Web app) as of
  // 2026-07-28. Safe to run locally without extra care: the Firebase Local
  // Emulator Suite (see firebase.json) intercepts Auth/Firestore calls
  // whenever the app is launched with --dart-define=USE_FIREBASE_EMULATOR=true,
  // regardless of the real project id here - no traffic reaches these real
  // servers in that mode. Without that flag, calls go to the real project,
  // so always pass it for local dev/testing.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBboLFz_5VrbeogNev7Mp7CZdOtKsrHA9o',
    appId: '1:834498413104:web:258bdd6af44b4db810a3f5',
    messagingSenderId: '834498413104',
    projectId: 'my-flutter-init',
    authDomain: 'my-flutter-init.firebaseapp.com',
    storageBucket: 'my-flutter-init.firebasestorage.app',
    measurementId: 'G-PKF7S1DG7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'demo-io-pinball-api-key',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'demo-io-pinball',
    storageBucket: 'demo-io-pinball.appspot.com',
  );
}
